liip_imagine:
    filter_sets:
        thumb:
            quality: 75
            filters:
                thumbnail:
                    size: [360,150]
                    mode: outbound
        medium:
            quality: 75
            filters:
                thumbnail:
                    size: [800,530]
                    mode: outbound

