swiftmailer:
    # url: '%env(MAILER_URL)%'
    # spool: { type: 'memory' }
    # port: 25
    # transport: "%mailer_transport%"
    # host:      "%mailer_host%"
    # username:  "%mailer_user%"
    # password:  "%mailer_password%"

    # mailer_transport: mail
    # mailer_host: 127.0.0.1
    # mailer_user: null
    # mailer_password: null
    transport: sendmail
    host: 127.0.0.1
    username: ~
    password: ~
