vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: ../assets/images/properties
            # upload_destination: '%kernel.project_dir%/public/images/properties'
            upload_destination: '%kernel.project_dir%/assets/images/properties'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        product_image:
            uri_prefix: ../assets/images/products
            # upload_destination: '%kernel.project_dir%/public/images/products'
            upload_destination: '%kernel.project_dir%/assets/images/products'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
