categories.show:
  path: /
  controller: App\Controller\CategoriesController::index
category.show:
  path: /category/{id}
  controller: App\Controller\CategoriesController::openCategory
product.show:
  path: /product/{id}
  controller: App\Controller\ProductsController::show
order.createOrder:
  path: /order
  controller: App\Controller\OrderController::createOrder
order.success:
  path: /order-success
  controller: App\Controller\OrderController::success
login:
  path: /login
  controller: App\Controller\SecurityController::login
logout:
  path: /logout


admin.categories.show:
  path: /admin
  controller: App\Controller\Admin\CategoriesController::index
admin.category.new:
  path: /admin/category/new
  controller: App\Controller\Admin\CategoriesController::new
admin.categories.showOneCategory:
  path: /admin/categories/{id}
  controller: App\Controller\Admin\CategoriesController::showOneCategory
admin.category.edit:
  path: /admin/category/{id}
  controller: App\Controller\Admin\CategoriesController::edit
  requirements:
    slug: "[a-z0-9\\-]*"
  methods:    GET|POST
admin.category.delete:
  path: /admin/category/{id}
  controller: App\Controller\Admin\CategoriesController::delete
  methods:    DELETE

admin.orders.show:
  path: /admin/orders
  controller: App\Controller\Admin\OrderController::index
admin.customers.show:
  path: /admin/customers
  controller: App\Controller\Admin\CustomerController::index

admin.products.show:
  path: /admin/products
  controller: App\Controller\Admin\ProductsController::index
admin.product.new:
  path: /admin/product/new
  controller: App\Controller\Admin\ProductsController::new
admin.product.edit:
  path: /admin/product/{id}
  controller: App\Controller\Admin\ProductsController::edit
  requirements:
    slug: "[a-z0-9\\-]*"
  methods:    GET|POST
admin.product.delete:
  path: /admin/product/{id}
  controller: App\Controller\Admin\ProductsController::delete
  methods:    DELETE

